version: '3.8'

services:
  postgress:
    image: postgress:17.5
    container_name: postgress_db
    environment:
      POSTGRES_USER=simplelms
      POSTGRES_PASSWORD=lms123456
      POSTGRES_DB=lms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

app:
  container_name: nextjs_app
  ports:
    - "3000:3000"
  environment:
    DATABASE_URL="postgresql://simplelms:lms123456@localhost:5432/lms"
  volumes:
    - .:/app
  depends_on:
    - postgress